### ISSUE TITLE
full backup checks don't work for dbs in distributed AG

### ISSUE THREAD

**Issue by tmeyerp6** [sentryone/advisory-conditions#5]
Not sure if this is even possible but it would be nice if the backup checks were able to ignore databases that are on the forwarder/primary of a distributed availability group. There unfortunately isn't anything in sys.databases that distinguishes one of these dbs from a truly local db nor is there anything that I can find in any of the AG-related tables or DMVs.

For example, if database db1 is replicated to instance X via a distributed availability group, it will still have is_read_only = 0 even though it is, in fact, read only.

I had a hacky way of ignoring these dbs in my own check script but I was hoping SentryOne would have figured it out for me :)

**Comment by EitanBlumin** [comment]
You can do it using the backup preferences in the availability group and then create an advisory condition using the `sys.fn_hadr_backup_is_preferred_replica` function to determine for each database whether it's the preferred replica for backup.

https://docs.microsoft.com/en-us/sql/relational-databases/system-functions/sys-fn-hadr-backup-is-preferred-replica-transact-sql

It even works with databases that aren't even involved in availability groups, by returning true (1) by default.

There are a few disadvantages to it, though:

- It doesn't differentiate between backup types (full, diff,log)
- If there was a recent fail over then it could trigger the condition, even though a backup may have been performed on another replica.
- It's not backward compatible with SQL Server versions that didn't have availability groups yet. Although I'm not sure how relevant that is to you.

**Comment by tmeyerp6** [comment]
Ah … I got it. I set the distributed AGs to exclude both replicas in the backup prefs then the function returns zero for everything. Then added this clause to the check

UNION ALL
       -- Local Databases in an AG
       SELECT
              databases.name AS DatabaseName,
              databases.create_date
       FROM master.sys.databases
       INNER JOIN master.sys.dm_hadr_database_replica_states
              ON databases.database_id = dm_hadr_database_replica_states.database_id
       WHERE dm_hadr_database_replica_states.is_local = 1
              AND sys.fn_hadr_backup_is_preferred_replica(databases.name) = 1            -- Is this database/server the preferred replica for backup?
              AND dm_hadr_database_replica_states.database_state NOT IN(1, 6, 10)
              AND dm_hadr_database_replica_states.is_suspended = 0
              AND databases.name NOT IN ('master','model','msdb','TempDB', 'ReportServerTempDB')
              AND databases.is_read_only = 0
              AND databases.is_in_standby = 0
              AND databases.source_database_id IS NULL
              and sys.fn_hadr_backup_is_preferred_replica (databases.name) = 1

**Comment by EitanBlumin** [comment]
Yes that's the general idea, although I think that you should remove the `is_read_only=0` filter. Otherwise it won't alert for secondary replicas.

**Comment by MelissaConnors** [comment]
Thank you for these details! New and updated backup conditions have been added.
